### PR TITLE
Fix Pdf.js api accesses through obsidian

### LINKED ISSUE #5: "Extract Markdown From PDFs" not generating any markdown files, only folder structure
Obsidian v0.14.10, installer version 0.13.30, plugin version 0.1.5, Ubuntu 21.04.

I've tried this plugin on two different vaults and three different folders of PDFs: one large (1700 files), one medium (180 files), one small (40 files). I've tried with all default settings as well as customized settings.

In almost all cases, when I run the "Extract Markdown From PDFs" command, the plugin correctly reconstructs the folder structure of my PDF folder under Generated/, but creates no markdown files. In one (seemingly anomalous) case, a single markdown file was produced. I ran the plugin on this same vault/folder combination and had it produce 0 markdown files, so I'm unsure why it produced only one in one of my tests.

The plugin is not generating any messages in Obsidian or log files that I can find, so I don't know where to begin diagnosing what could be wrong. Please advise. The functionality looks great and I'd love to be able to use it!

### PR DESCRIPTION
**Pull request by Razboy20**
fixes #5, (and #7, #12, #13, but it's all the same).

Also added typings for Pdf.js within the project, so future upstream breaking changes will be easier to spot.

### CODE REVIEW

**Comment by silvia0801** [comment]
这个版本怎么使用呢？

**Review by PT123123 — APPROVED** [review]
LGTM. works for me.

**Comment by Razboy20** [comment]
@liammagee please let me know if there is anything I can do to help get this merged in. 😄

**Comment by liammagee** [comment]
Thanks very much - I've merged your PR after a long delay. Hopefully that
resolves a number of the outstanding issues.

Liam.

**Pull request merged**
